version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    command: ["python", "main.py", "--create-db", "--run-server"]
    volumes:
      - ./backend/test.db:/app/test.db